# Generated by Django 4.2.13 on 2024-12-14 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_genre"),
    ]

    operations = []
