# Generated by Django 4.2.13 on 2024-12-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_fix_invalid_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="blood_pressure",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bmi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="education",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Some High School"),
                    (2, "High School Graduate"),
                    (3, "Some College"),
                    (4, "College Graduate"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.IntegerField(
                blank=True, choices=[(1, "Male"), (0, "Female")], null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="glucose_level",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="heart_rate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
