# Generated by Django 4.2.13 on 2024-12-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("male", models.IntegerField(choices=[(1, "Male"), (0, "Female")])),
                ("age", models.PositiveIntegerField()),
                (
                    "education",
                    models.IntegerField(
                        choices=[
                            (1, "Some High School"),
                            (2, "High School Graduate"),
                            (3, "Some College"),
                            (4, "College Graduate"),
                        ]
                    ),
                ),
                ("current_smoker", models.BooleanField()),
                ("cigs_per_day", models.FloatField(blank=True, null=True)),
                ("bp_meds", models.BooleanField()),
                ("prevalent_stroke", models.BooleanField()),
                ("prevalent_hyp", models.BooleanField()),
                ("diabetes", models.BooleanField()),
                ("tot_chol", models.FloatField()),
                ("sys_bp", models.FloatField()),
                ("dia_bp", models.FloatField()),
                ("bmi", models.FloatField()),
                ("heart_rate", models.PositiveIntegerField()),
                ("glucose", models.FloatField()),
                ("ten_year_chd", models.BooleanField(default=False)),
            ],
        ),
    ]
