# Generated by Django 4.2.13 on 2024-12-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heartrisk", "0002_chdrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chdrecord",
            name="glucose",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
